version: '3'

services:
  web:
    image: nginx:latest
    build: .
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
